version: '3.8'

services:
  firebase-emulator:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    ports:
      - "4000:4000"  # Firebase UI
      - "5000:5000"  # Hosting
      - "5001:5001"  # Functions
      - "8080:8080"  # Firestore
      - "9099:9099"  # Auth
      - "9199:9199"  # Storage
    volumes:
      - .:/workspace
      - /workspace/node_modules
    working_dir: /workspace
    command: >
      sh -c "firebase emulators:start --only auth,firestore,functions,hosting,storage --project demo-project"
    environment:
      - FIREBASE_TOKEN=
      - GOOGLE_APPLICATION_CREDENTIALS=
    networks:
      - golf-network

  seed-data:
    image: node:18
    volumes:
      - .:/workspace
      - /workspace/node_modules
    working_dir: /workspace
    command: >
      sh -c "npm install &&
             sleep 20 &&
             node scripts/seed-data.js"
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulator:9199
      - GCLOUD_PROJECT=demo-project
      - GOOGLE_CLOUD_PROJECT=demo-project
    depends_on:
      - firebase-emulator
    networks:
      - golf-network

  app:
    image: node:18
    ports:
      - "3000:3000"  # Vite dev server
    volumes:
      - .:/workspace
      - app_node_modules:/workspace/node_modules
    working_dir: /workspace
    command: >
      sh -c "npm install &&
             npm run dev -- --host 0.0.0.0 --port 3000"
    environment:
      - VITE_FIREBASE_USE_EMULATOR=true
      - VITE_FIREBASE_PROJECT_ID=demo-project
      - VITE_ENVIRONMENT=local
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
    depends_on:
      - firebase-emulator
    networks:
      - golf-network

volumes:
  app_node_modules:

networks:
  golf-network:
    driver: bridge
